# Generated by Django 4.2.3 on 2023-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
